services:
  mysql:
    image: mysql:${DOCKER_MYSQL_VERSION}
    container_name: ${DOCKER_MYSQL_CONTAINER_NAME}
    env_file: .env
    ports: ["3306:3306", "33060:33060"]
    volumes: [mysql_data:/var/lib/mysql:rw]
    user: ${UID}:${GID}

volumes:
  mysql_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${MYSQL_DATA_DIR}
