services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql

volumes:
  mysql_data:
